SUSPICIOUS_KEYWORDS = (
    "login",
    "secure",
    "verify",
    "update",
    "bank",
    "account",
    "password",
    "confirm",
    "support",
)

TRUSTED_DOMAINS = (
    "google.com",
    "apple.com",
    "paypal.com",
    "microsoft.com",
    "amazon.com",
    "youtube.com",
    "shein.com",
    "facebook.com",
    "instagram.com",
    "netflix.com",
    "linkedin.com",
    "whatsapp.com",
    "tiktok.com",
    "xero.com",
    "mygov.au",
    "commbank.com.au",
    "nab.com.au",
    "westpac.com.au",
    "anz.com.au",
)

BRAND_TARGETS = (
    "google",
    "apple",
    "paypal",
    "microsoft",
    "amazon",
    "facebook",
    "netflix",
    "youtube",
    "shein",
    "instagram",
    "linkedin",
    "whatsapp",
    "tiktok",
    "xero",
    "mygov",
    "commbank",
    "westpac",
)

TRUSTED_HOSTNAME_TOKENS = (
    "google",
    "amazon",
    "microsoft",
    "paypal",
    "apple",
    "youtube",
    "shein",
    "facebook",
    "instagram",
    "netflix",
    "linkedin",
    "whatsapp",
    "tiktok",
    "xero",
    "mygov",
    "commbank",
    "nab",
    "westpac",
    "anz",
    "canberra",
    "uclearn",
)

HIGH_RISK_TLDS = {".xyz", ".top", ".info", ".click", ".loan"}
MEDIUM_RISK_TLDS = {".online", ".site", ".store", ".biz"}
